### PR TITLE
Several necessary changes for Intermezzo 2023-10-26.

### PR DESCRIPTION
**Pull request by swampatha**
This adds the "No Speed Cap" code by Gabriela_ to the 200cc code lists for all regions. This was tested with NTSC-U, but should cause no problems for all regions.

### CODE REVIEW

**Comment by swampatha** [comment]
The latest commit also updates the bundled LE-CODE binaries for both the Generator and the Patcher to Build 39 to utilize the custom cup icon size that's required for Intermezzo 2023-10-26. This also removes the duplicate LE-CODE binaries in the clean files for the Generator, as the two sets of files were identical.

**Comment by Krummers** [comment]
Please revert the "Split LE-CODE binaries" edits, as they crash the script. What you can do is copy the same files in the two folders and revert the code alterations. This is the best option for now, since issue #51 exists. (I also lack the time to look into the code and fix it.)

**Comment by swampatha** [comment]
Done.

**Comment by Krummers** [comment]
The broken code can be updated at any time.

**Pull request merged**
